/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.itbaizhan.struts.action;

import javax.servlet.http.*;

import org.apache.struts.action.*;

import com.itbaizhan.ORM.*;
import com.itbaizhan.base.*;
import com.itbaizhan.service.*;
import com.itbaizhan.struts.form.MemLoginForm;

/** 
 * MyEclipse Struts
 * XDoclet definition:
 * @struts.action path="/login" name="memLoginForm" input="/default.jsp" parameter="method" scope="request" validate="true"
 */
public class LoginAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		MemLoginForm memLoginForm = (MemLoginForm) form;
		MemService service = new MemServiceImpl();
		ActionForward forward = null;
		ActionMessages msgs = new ActionMessages();
		try{
			Member mem = service.memLogin(memLoginForm.getLoginName(), memLoginForm.getLoginPwd());
			if (mem!=null){
				request.getSession().setAttribute("member", mem);
				forward = new ActionForward("/mer.do?method=browseIndexMer");
			}else{				
				forward = mapping.getInputForward();
				msgs.add("loginError",new ActionMessage(Constants.ADMIN_LOGINERROR_KEY));
				saveErrors(request, msgs);
			}
		}catch(Exception ex){
			logger.info("��ִ��LoginAction���е�login����ʱ���?\n");
			ex.printStackTrace();
		}
		return forward;
	}
	
	public ActionForward logout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		request.getSession().removeAttribute("member");
		return new ActionForward("/mer.do?method=browseIndexMer");
	}	
}